### ISSUE TITLE
Remove the unused requires_sqlalchemy_2 marker, or restore the sqlalchemy axis it needs

### ISSUE THREAD

**Issue by tschm** [schireson/pytest-alembic#211]
**Subcategory:** test design quality — 8 → 9
**Found by:** `/rhiza:quality` on `main` @ `da41949`

`requires_sqlalchemy_2` is defined at `tests/__init__.py:12` and referenced nowhere:

```
$ grep -rn requires_sqlalchemy_2 tests src
tests/__init__.py:12:requires_sqlalchemy_2 = pytest.mark.skipif(not is_sqlalchemy_2, reason="Requires v2")
```

`is_sqlalchemy_2` (`:6`) exists only to build it, so both lines are dead. They are
counted as covered because importing the module executes them — a case where the 100%
floor reports on code no test consults.

The marker is also unreachable by construction. `.github/workflows/build.yml:53` pins
`sqlalchemy-version: ["2.0.40"]`, so `is_sqlalchemy_2` is `True` in every CI entry and
the skip can never fire. `pyproject.toml`'s coverage comment already records this:

> The previous floor of 93 was set because the CI matrix skipped the asyncio tests on
> sqlalchemy versions without asyncio support. That reason is gone: the matrix pins a
> single sqlalchemy (2.0.40), so no entry skips them any more.

**Scope note:** the sibling symbols are *not* dead. `requires_asyncio_support` is applied
at `tests/test_runner.py:264`, `:270` and `:280`, and `sqlalchemy_version` /
`supports_asyncio` feed it. Only the `requires_sqlalchemy_2` / `is_sqlalchemy_2` pair
should be removed.

**done when** `tests/__init__.py` defines no unused symbol — either the pair is deleted,
or a sqlalchemy axis is restored to the matrix and the marker is applied to the tests
that need it.

**Comment by DanCardin** [comment]
the test suite does in fact work with sqlalchemy 1.4 today. so i'm much more apt to restore that test matrix entry than I am to remove the code you're referencing/removing in #216

**Comment by tschm** [comment]
Following up on:

> the test suite does in fact work with sqlalchemy 1.4 today. so i'm much more apt to restore that test matrix entry than I am to remove the code you're referencing/removing in #216

I went to verify that before acting on it, and the direction turns out to be right but the premise did not hold at the time — with a fix, it holds now.

**The suite had never actually run on 1.4.** Beyond the matrix pinning `sqlalchemy-version: ["2.0.40"]`, the dev group carried `sqlalchemy[asyncio]>=2.0.42`. Since the higher floor wins, every resolution — CI and local alike — landed on 2.0.42. Nothing in the repo ever exercised 1.4.

When I removed that dev pin, the async tests failed immediately:

```
AttributeError: 'Connection' object has no attribute 'commit'
  .../sqlalchemy/ext/asyncio/engine.py:288
```

`ConnectionExecutor.run_task` drove async engines with `engine.connect()` plus an explicit `await connection.commit()`. `AsyncConnection.commit` does not exist before sqlalchemy 2.0, so this hit **every** 1.4 release, not an edge of the range:

| sqlalchemy | before the fix |
|---|---|
| 1.4.24 (lowest reachable — pytest-mock-resources excludes 1.4.0–1.4.23) | `test_async_sqlalchemy` fails |
| 1.4.31 | fails |
| 1.4.40 | fails |
| 1.4.46 | fails |
| 1.4.54 (last 1.4) | fails |
| 2.0.0 | passes |

So `sqlalchemy>=1.4` was true for sync engines only; any user on 1.4 passing an async engine hit a hard `AttributeError`.

**#221 fixes that** rather than raising the floor — which I think is the outcome your comment was pointing at, and is why I closed #216 in favour of it. The change is one line: `engine.begin()` instead of `connect()` + explicit `commit()`. It is equivalent on the happy path (commits on success, rolls back on an exception) and exists across the whole declared range. After it, 1.4.24 / 1.4.54 / 2.0.0 / 2.0.52 all pass the full suite, and the `lowest-deps` job runs it at sqlalchemy 1.4.24 on every PR — verified from the job log, not just a green tick.

**For this issue specifically**, that cuts in an unexpected direction. Restoring the matrix axis is now genuinely viable where before it would have gone red, and I am happy to add it. But it does not by itself resolve the "done when": at sqlalchemy 1.4.24 the suite is **149 passed, 1 skipped**, and the single skip is `test_config.py::test_pyproject_toml`, which skips on the *alembic* version and has nothing to do with sqlalchemy. Nothing in the suite requires v2 any more.

So a restored axis would make `requires_sqlalchemy_2` *fireable* but still *unused* — it would remain an unreferenced symbol in `tests/__init__.py` unless a test is marked with it, and there is currently no test that needs it. `is_sqlalchemy_2` exists only to build the marker.

That leaves two coherent endings, and I am glad to do either:

1. **Restore the sqlalchemy axis and delete the `requires_sqlalchemy_2` / `is_sqlalchemy_2` pair.** The axis gives you the 1.4 coverage you want; the marker goes because nothing requires v2. `requires_asyncio_support`, `sqlalchemy_version` and `supports_asyncio` all stay — they are live and applied at `tests/test_runner.py:264`, `:270`, `:280`.
2. **Restore the axis and keep the pair**, if you would rather hold the marker for a future v2-only test. Worth being explicit that it is deliberate, since it will otherwise keep reading as dead code.

Either way I would suggest keeping this open until the marker question is settled — the axis alone does not close it.

**Comment by DanCardin** [comment]
With the lower bound in place, if there's no test difference remaining that requires requires_sqlalchemy_2 / is_sqlalchemy_2, then we can remove those symbols/markers.
